# Generated by Django 5.2.7 on 2025-10-12 13:53

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_fix_images_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.project_image_upload_path),
        ),
        migrations.AddField(
            model_name='thought',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.thought_image_upload_path),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.work_image_upload_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Additional image URLs'),
        ),
    ]
