# Generated by Django 5.2.7 on 2025-10-12 13:53

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Additional image URLs'),
        ),
    ]
