# Generated by Django 5.2.7 on 2025-10-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_contact', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=10)),
                ('class_type', models.CharField(choices=[('web', 'Web Development'), ('react', 'React Frontend'), ('django', 'Django Backend'), ('flutter', 'Flutter Mobile'), ('scratch programming', 'Scratch Programming for Kids')], max_length=50)),
                ('class_option', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('declined', 'Declined')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learn Inquiry',
                'verbose_name_plural': 'Learn Inquiries',
                'db_table': 'learn_inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
